
version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - CERTBOT_EMAIL
      - STAGING
      - DHPARAM_SIZE
      - RSA_KEY_SIZE
      - ELLIPTIC_CURVE
      - USE_ECDSA
      - RENEWAL_INTERVAL
      - DEBUG
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx_conf.d:/etc/nginx/user_conf.d


  app:
    image: 542185263552.dkr.ecr.us-east-1.amazonaws.com/starshield-staging/CI-Docker-AWS:latest
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  nginx_secrets: